Section.create(:name => "win", :per_page => 1, :frontpage => true)
Section.create(:name => "leap", :per_page => 2, :frontpage => true)
Section.create(:name => "think", :per_page => 2, :frontpage => true)
Section.create(:name => "CGOIB", :per_page => 2, :frontpage => false)
Page.create(:title => 'About this site', :slug => 'about', :body => 'Something about this site.')
