Section.create(:name => "win", :per_page => 1)
Section.create(:name => "leap", :per_page => 2)
Section.create(:name => "think", :per_page => 2)
Section.create(:name => "tweet", :per_page => 5)
Page.create(:title => 'About this site', :slug => 'about', :body => 'Something about this site.')
